# Generated by Django 3.0.2 on 2020-01-23 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('national_code', models.CharField(max_length=11)),
                ('personal_code', models.CharField(max_length=15)),
                ('phone_number', models.CharField(max_length=11)),
                ('address', models.CharField(max_length=50)),
                ('married', models.BooleanField()),
                ('age', models.IntegerField()),
                ('wage', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
