# Generated by Django 3.0.2 on 2020-01-25 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(default='male', max_length=10),
            preserve_default=False,
        ),
    ]
